# Generated by Django 4.2.3 on 2023-09-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='questions.question'),
        ),
    ]
