version: "3"

services:
  app:
    container_name: fcisoverflow-app-container
    ports:
      - "3000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rengo
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=FCISOverflow
      - PGDATA=/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  # nginx:  
  #   image: nginx
  #   volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #    - static_volume:/home/app/web/staticfiles
  #    - media_volume:/home/app/web/mediafiles
  #   ports:
  #    - "9000:80"
  #   depends_on:
  #     - littlelemon-app



volumes:
  postgres_data:
  cache:
    driver: local
